package lox;

import lox.Expr.Binary;
import lox.Expr.Grouping;
import lox.Expr.Literal;
import lox.Expr.Unary;

/* 
 * The interpretor evaluates the AST that the parser produced
 *  it's implemented as a visitor instead of stuffing that
 * logic inside each node, similar to how we did the printer 
 */

/*
 * To support dynamic types in Lox
 * we use Object to correspond to our
 * variables in Java, in runtime we can
 * check what the variable's type is
 * bec. JVM supports type checking in
 * runtime
 */

public class Interpretor implements Expr.Visitor<Object> {

    /*
     * Takes in the syntax tree
     * generated by the parser & kicks
     * off the evalution chain.
     */
    void interpret(Expr expression) {
        try {
            Object value = evaluate(expression);
            System.out.println(stringify(value));
        }
        // Catch our custom runtime exception
        catch (RuntimeError error) {
            Lox.runtimeError(error);
        }
    }

    /*
     * A literal is our last stop,
     * similar to how primary was during
     * parsing
     */
    @Override
    public Object visitLiteralExpr(Literal expr) {
        return expr.value;
    }

    /*
     * A grouping expr only has one sub
     * expression, so we evaluate that
     * & return the value
     */
    @Override
    public Object visitGroupingExpr(Grouping expr) {
        return evaluate(expr.expression);
    }

    /*
     * Unary evaluates it's sub expr
     * and then does it's own action
     * (P.S: A unary can be ! or -)
     * 
     * We're basically doing a post order
     * traversal of the AST, an expr can't
     * evaluate it's value before it's children
     */
    @Override
    public Object visitUnaryExpr(Unary expr) {

        // Get the value for right sub expr
        Object right = evaluate(expr.right);

        switch (expr.operator.type) {
            case MINUS:
                checkNumberOperand(expr.operator, right);
                // We're casting to a double in runtime bec. we
                // can't know type statically
                return -(double) right;

            case BANG:
                return !isTruthy(right);

        }

        // Unreachable
        return null;
    }

    @Override
    public Object visitBinaryExpr(Binary expr) {

        // This order is part of the language semantics
        // Binary expressions are evaluated left to right
        Object left = evaluate(expr.left);
        Object right = evaluate(expr.right);

        switch (expr.operator.type) {
            case GREATER:
                checkNumberOperand(expr.operator, left, right);
                return (double) left > (double) right;
            case GREATER_EQUAL:
                checkNumberOperand(expr.operator, left, right);
                return (double) left >= (double) right;
            case LESS:
                checkNumberOperand(expr.operator, left, right);
                return (double) left < (double) right;
            case LESS_EQUAL:
                checkNumberOperand(expr.operator, left, right);
                return (double) left <= (double) right;
            case MINUS:
                checkNumberOperand(expr.operator, left, right);
                return (double) left - (double) right;
            case PLUS:
                if (left instanceof Double && right instanceof Double)
                    return (double) left + (double) right;

                if (left instanceof String && right instanceof String)
                    return (String) left + (String) right;

                throw new RuntimeError(
                        expr.operator,
                        "Operands must be two numbers or two strings.");
            case SLASH:
                checkNumberOperand(expr.operator, left, right);
                return (double) left / (double) right;
            case STAR:
                checkNumberOperand(expr.operator, left, right);
                return (double) left * (double) right;
            case BANG_EQUAL:
                return !isEqual(left, right);
            case EQUAL_EQUAL:
                return isEqual(left, right);

        }

        // Unreachable
        return null;
    }

    private void checkNumberOperand(Token operator, Object operand) {
        if (operand instanceof Double)
            return;

        throw new RuntimeError(operator, "Operand must be a number");
    }

    private void checkNumberOperand(Token operator, Object left, Object right) {
        if (left instanceof Double && right instanceof Double)
            return;

        throw new RuntimeError(operator, "Operands must be numbers");
    }

    /*
     * This method defines what our language
     * considers truthy or falsey.
     */
    private boolean isTruthy(Object object) {
        if (object == null)
            return false;
        if (object instanceof Boolean)
            return (boolean) object;

        // Everything else is true, empty strings, empty lists, etc..
        return true;
    }

    /*
     * This method is as important as isTruhty()
     * It defines the notion of equality for Lox in
     * terms of it's Java implementation
     */
    private boolean isEqual(Object a, Object b) {
        if (a == null && b == null)
            return true;
        if (a == null)
            return false;

        // No implicit conversions
        // '3' != 3
        return a.equals(b);
    }

    /*
     * The same idea as print() in ASTPrinter.
     * Given an expression, this method calls
     * accept() of that expression & passes
     * to it this (which is the visitor instance).
     * That way the expression calls the appropriate
     * method for itself (visitBinaryExpr, visitUnaryExpr, etc..)
     * & returns the value.
     */

    private Object evaluate(Expr expr) {
        return expr.accept(this);
    }

    // A util to print a value based on it's runtime type
    // Another bridge between Lox & Java (like isEqual & isTruthy)
    private String stringify(Object object) {
        if (object == null)
            return "nil";

        if (object instanceof Double) {
            String text = object.toString();
            if (text.endsWith(".0")) {
                text = text.substring(0, text.length() - 2);
            }
            return text;
        }

        return object.toString();
    }

}
